
name: sonar-c
on:
  push:
    branches: '*'
    paths:
      - 'c-icap/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'c-icap/**'
jobs:
  build:
    runs-on: ubuntu-latest
    container: glasswallsolutions/icap-c-base:latest
    steps:
        - name: Checkout Project
          uses: actions/checkout@v1
          with:
            submodules: true

        - name: build c-icap
          run: cd c-icap &&  autoreconf -i && ./configure --prefix=/usr/local/c-icap && /opt/build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir build_wrapper_output_directory make install

        - name: scan c-icap
          run: cd c-icap && /opt/sonar-scanner-4.4.0.2170-linux/bin/sonar-scanner
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
